In [1]:
c=3
print(c)

3


In [2]:
Hello i am rahul prajapt 

SyntaxError: invalid syntax (<ipython-input-2-cb77bed10e2e>, line 1)

Hello i am rahul prajapt 


## dddd 


In [3]:
# hwllo fo os la  jlidn sl 

In [1]:
print("ehlllo ")

ehlllo 


In [2]:
print("4*4+3")

4*4+3


In [3]:
#include 


In [4]:
print("hello ")

hello 


In [5]:
print(3+3)

6


In [6]:
a=9

In [7]:
int a=9;


SyntaxError: invalid syntax (<ipython-input-7-9465e7734eaf>, line 1)

In [8]:
int a=0

SyntaxError: invalid syntax (<ipython-input-8-1af7c4477ccd>, line 1)

In [9]:
a=3
v=4
b=a+v

In [10]:
a=9
b=3
c=a+b
print(c)

12


In [1]:
 print("hello this is priyabka
       ")

SyntaxError: EOL while scanning string literal (<ipython-input-1-368bd48fa114>, line 1)

In [2]:
print("hello")

hello


In [3]:
import numpy as np
a=np.array([1.0,2.0][3.0,4.0])
print(a)

<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<ipython-input-3-1a6b97fbf91b>:2: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  a=np.array([1.0,2.0][3.0,4.0])


TypeError: list indices must be integers or slices, not tuple

In [4]:
import numpy as np

In [5]:
a=np.array([1.0,2.0][3.0,4.0])
print(a)


<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<ipython-input-5-3bda5ae60e69>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  a=np.array([1.0,2.0][3.0,4.0])


TypeError: list indices must be integers or slices, not tuple

In [6]:
a=([1.0,2.0], [3.0,4.0])
print(a)

([1.0, 2.0], [3.0, 4.0])


In [7]:
type (a)

tuple

In [8]:
A=([1.0,4.0],[2.0,3.0,1,2])

In [9]:
A=np.array([1,2,3],[3,4,5])

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [10]:
A=np.array([1,2,3],[3,4,5])
print(A)

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [11]:
import numpy as np

In [12]:
A=np.array([1, 2, 2], [2, 3, 4])
print(A)

TypeError: Field elements must be 2- or 3-tuples, got '2'

In [13]:
A=np.array([[1, 2, 2], [2, 3, 4]])
print(A)

[[1 2 2]
 [2 3 4]]


In [14]:
import numpy as np
a=np.array([[2],[2],[4]])
print(a)

[[2]
 [2]
 [4]]


In [15]:
# row vomment 

In [16]:
a=np.array([2, 2, 3 ,4])
print(a)

[2 2 3 4]


In [17]:
A=np.array([2,3,4,5])
B=np.array([1,22,3,6])
print(A,B)

[2 3 4 5] [ 1 22  3  6]


In [18]:
A=np.array([2,3,4,5])
B=np.array([1,22,3,6])
C=np.array([2],[3],[4])
D=np.array([3],[5],[6])

C=A+B
print("C=",C)

C= [ 3 25  7 11]


In [19]:
A=np.array([2,3,4,5])
print(A.transpose())

[2 3 4 5]


In [25]:
A=np.array([2,3,4,5])
print(A.transpose)

<built-in method transpose of numpy.ndarray object at 0x0000013051209210>


In [27]:
C=np.array([2],[3])
print(C.transpose())

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [30]:
import numpy as np

A=np.array([2,3,4])
B=np.array([1,22,3])
C=np.array([2],[3],[4])
D=np.array([3],[5],[6])
print(D.transpose())

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [31]:
import numpy as np
V=np.array([2,3,4])
c=2
print("The vectore v1",V)
print("THe vector xcv",c*V)

The vectore v1 [2 3 4]
THe vector xcv [4 6 8]


In [1]:
import numpy as np
a=np.array([2,4,5,5])
print(a)

[2 4 5 5]


In [3]:
a=5
b=55
b=a/b
print(b)

0.09090909090909091


In [4]:
z=4
z

4

In [4]:
"ehllo"+"is "+" hehel "

'ehllois  hehel '

In [5]:
print('hello')

hello


In [6]:
print('hello is hello')

hello is hello


In [7]:
8+"7"

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [8]:
...


Ellipsis

In [9]:
age=input("what is your name?")

what is your name?rahul 


In [13]:
import numpy as np
a=np.array([2,4,5,6])
b=np.array([2],[3],[5])

print(b.transpose())

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [18]:
import numpy as np
A=input(np.array([]))
#A=np.array([2,3],[5,7])
#print(A.transpose())

[]4,43,3,2


In [21]:
import numpy as np
A=np.array([0,2,3,4])
B=np.array([6,7,8,9])
opaa=np.outer(A,B)
opab=np.outer(B,A)
print("A",A)
print("outer product",opaa)
print("outer prod B",opab)

A [0 2 3 4]
outer product [[ 0  0  0  0]
 [12 14 16 18]
 [18 21 24 27]
 [24 28 32 36]]
outer prod B [[ 0 12 18 24]
 [ 0 14 21 28]
 [ 0 16 24 32]
 [ 0 18 27 36]]


In [29]:
import numpy as np
A=np.array([[1,2,3],[5,6,7]]) #2x3
B=np.array([[1,1],[2,1],[3,-3]]) #3x2

D=A.dot(B) # same multiplication 
print("D",D) # 2x2
#a=A*B
#print(a)

P=np.array([[3,4,5],[1,2,3]]) #2x3
Q=np.array([[1,1,2],[3,4,5]]) #2x3

#s=P.dot(Q)
S=P*Q
print("S",S)

D [[ 14  -6]
 [ 38 -10]]
S [[ 3  4 10]
 [ 3  8 15]]


In [45]:
import numpy as np
A=np.array([[1],[3],[4],[5]])
B=np.array([[2],[4],[6],[5]])
#B=A.transpose()  eroor
S=np.inner(A,B)
print("s ",S)

s  [[ 2  4  6  5]
 [ 6 12 18 15]
 [ 8 16 24 20]
 [10 20 30 25]]


In [53]:
import numpy as np
V1=np.array([4,5,6,7])
V2=np.array([[4],[5],[6],[7]])
V3=V1.transpose()
R1=V1.dot(V2)

print(R1)
print(type(R1))
R2=V1.dot(V1)
print(R2)
print(type(R2))
print(np.shape(V3))

V4=V1.dot(V3)
print(V4)

[126]
<class 'numpy.ndarray'>
126
<class 'numpy.int32'>
(4,)
126


In [56]:
import numpy as np
V1=np.array([[1,2,3],[2,3,5],[3,6,8],[2,4,3]])
V2=np.array([[2],[3],[4]])
print(V1.shape)
print(V2.shape)
R=V1.dot(V2)
print(R)
print(type(R))

(4, 3)
(3, 1)
[[20]
 [33]
 [56]
 [28]]
<class 'numpy.ndarray'>


In [69]:
import numpy as np
x=np.arange(9).reshape((3,3))

print(x)
#x=np.array([1,2,3])
np.diag(x)
print("x1",np.diag(x))

np.diag(x,k=1)
print(x)

np.diag(x,k=-1)
print(x)

y=np.diag(np.diag(x))
print(y)

z=np.diag([5,6,7])
print(z)

v=np.diag([3,4,5])
print(v)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
x1 [0 4 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 0 0]
 [0 4 0]
 [0 0 8]]
[[5 0 0]
 [0 6 0]
 [0 0 7]]
[[3 0 0]
 [0 4 0]
 [0 0 5]]


In [72]:
x=np.array([2,3,4])
y=np.diag(x,k=0)
print(y)

[[2 0 0]
 [0 3 0]
 [0 0 4]]


In [73]:
x=np.array([2,3,4])
y=np.diag(x,k=-1)
print(y)

[[0 0 0 0]
 [2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]]


In [74]:
x=np.array([2,3,4])
y=np.diag(x,k=1)
print(y)

[[0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]
 [0 0 0 0]]


In [96]:
import numpy as np
I=np.eye(3)
print(" I",I)

A=np.array([[1,2,3,4],[3,45,8],[4,8,87]])
print(A)

ai=np.matmul(A,I)
print(ai)

if ai.all()==A.all():
    print("AI is A")

 I [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[list([1, 2, 3, 4]) list([3, 45, 8]) list([4, 8, 87])]


<ipython-input-96-8f3290633544>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  A=np.array([[1,2,3,4],[3,45,8],[4,8,87]])


TypeError: can't multiply sequence by non-int of type 'float'

In [97]:
import numpy as np
M=np.array([[2,3,4],[3,45,8],[4,8,78]])
print(M)
detA=np.linalg.det(M)
print(detA)


[[ 2  3  4]
 [ 3 45  8]
 [ 4  8 78]]
5661.9999999999945


In [1]:
print ("Rhal  us bsi bjd hud ".lower())

rhal  us bsi bjd hud 


In [3]:
food=input("what is your favorite food")
supplies = " pen pecnicl color ruler "
print ('pen' in supplies)

what is your favorite fooddd
True


In [12]:
def food():
    print("hello")
food()    
    
    

hello


In [11]:
food()

TypeError: 'str' object is not callable

In [1]:
def food():
    print(3+3)
food()    

6


In [5]:
import numpy as np
a=np.array([[2],[3],[6]])
b=np.array([[2,3,4],[5,5,6]])
print(b.transpose())
print(a)
print(b)


[[2 5]
 [3 5]
 [4 6]]
[[2]
 [3]
 [6]]
[[2 3 4]
 [5 5 6]]


In [14]:
import numpy as np
M=np.array([[2,2,2],[2,4,3],[4,8,7]])
a=np.linalg.inv(M)
print(a)


[[ 1.   0.5 -0.5]
 [-0.5  1.5 -0.5]
 [-0.  -2.   1. ]]
