Introduction to Google Colaboratory, Python, NumPy, Pandas, Matplotlib and other relevant libraries

##Introduction

Python is a great general-purpose programming language on its own, but with the help of a few popular libraries (numpy, scipy, matplotlib, pandas) it becomes a powerful environment for scientific computing.

We expect that many of you will have some experience with Python and numpy; for the rest of you, this section will serve as a quick crash course both on the Python programming language and on the use of Python for scientific computing.

In this tutorial, we will cover:

* Notebooks and Google Colab
* Basic Python: Basic data types (Containers, Lists, Dictionaries, Sets, Tuples), Functions, Classes
* Numpy: Arrays, Array indexing, Datatypes, Array math, Broadcasting
* Matplotlib: Plotting, Subplots, Images
* Pandas and Seaborn: A brief introduction 

**What is a Jupyter notebook ?**

* A Jupyter notebook lets you write and execute Python code locally in your web browser. 
* Jupyter notebooks make it very easy to tinker with code and execute it in bits and pieces; for this reason they are widely used in scientific computing. 

**What is a Google Colab ?**
* Colaboratory, or "Colab" for short, is Google’s flavor of Jupyter notebooks that is particularly suited for machine learning and data analysis and that runs entirely in the cloud. 
* Colab is free to use, requires no setup, comes preinstalled with many packages, and benefits from free access to hardware accelerators like GPUs and TPUs (with some caveats).

## A Brief Note on Python Versions

As of Janurary 1, 2020, Python has [officially dropped support](https://www.python.org/doc/sunset-python-2/) for `python2`. We'll be using Python 3.6.9 for this iteration of the course. You can check your Python version at the command line by running `python --version`.

In [ ]:
!python --version

##Basics of Python

Python is an interpreted, high-level, general-purpose programming language. Python code is often said to be almost like pseudocode, since it allows you to express very powerful ideas in very few lines of code while being very readable.

###Basic data types

####Numbers

Integers and floats work as you would expect from other languages:

In [ ]:
x = 3
print(x)        # Printing the value of the variable
print(type(x))  # Printing the data type of the variable

In [ ]:
print(x + 1)   # Addition
print(x - 1)   # Subtraction
print(x * 2)   # Multiplication
print(x / 2)   # Divison
print(x // 2)  # Floor Divison
print(x ** 2)  # Exponentiation
print(x ** 3)

In [4]:
# Shorthand operators
x=5
x += 1     # x = x + 1
print(x)
x *= 2     # x = x * 2
print(x)
x

6
12


12

In [ ]:
y = 2.5
print(type(y))
print(y, y + 1, y * 2, y ** 2)

Note that unlike many languages, Python does not have unary increment (`x++`) or decrement (`x--`) operators.

Python also has built-in types for long integers and complex numbers; you can find all of the details in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#numeric-types-int-float-long-complex).

####Booleans

Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (`&&`, `||`, etc.):

In [ ]:
t, f = True, False
print(type(t))
print(t)

Now we let's look at the operations:

In [ ]:
print(t and f) # Logical AND;
print(t or f)  # Logical OR;
print(not t)   # Logical NOT;

####Strings

In [7]:
hello = 'hello'   # String literals can use single quotes
world = "world"   # or double quotes; it does not matter
print(hello)      # Printing the value of the string
print(len(hello)) # Printing the length of the string
str1 = "stc"

hello
5


In [8]:
hw = hello + ' ' + world  # String concatenation
print(hw)

hello world


In [9]:
hw12 = '{} {} {}'.format(hello, world, 12)  # string formatting
print(hw12)

hello world 12


String objects have a bunch of useful methods; for example:

In [5]:
s = "hello"
print(s.capitalize())  # Capitalize a string
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another
print('  world ')
print('  world '.strip())  # Strip leading and trailing whitespace

Hello
HELLO
he(ell)(ell)o
  world 
world


You can find a list of all string methods in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#string-methods).

###Containers

Containers are any object that holds an arbitrary number of other objects. Python includes several built-in container types: lists, dictionaries, sets, and tuples.

####Lists

A list is the Python equivalent of an array, but is resizeable and can contain elements of different types:

In [3]:
xs = [3, 1, 4]   # Create a list
print(xs, xs[2])
print(xs[-1])     # Negative indices count from the end of the list; prints "4"

[3, 1, 4] 4
4


In [4]:
xs[2] = 'foo'    # Lists can contain elements of different types
print(xs)

[3, 1, 'foo']


In [ ]:
xs.append('bar') # Add a new element to the end of the list
print(xs)  

In [ ]:
x = xs.pop()     # Remove and return the last element of the list
print(x, xs)

As usual, you can find all the gory details about lists in the [documentation](https://docs.python.org/3.7/tutorial/datastructures.html#more-on-lists).

####Slicing

In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing:

In [ ]:
nums = list(range(5))    # range is a built-in function that creates a list of integers
print(nums)         # Prints "[0, 1, 2, 3, 4]"

In [6]:
nums = list(range(5))    # range is a built-in function that creates a list of integers
print(nums)         # Prints "[0, 1, 2, 3, 4]"

print(nums[2:4])    # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])     # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])     # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])      # Get a slice of the whole list; prints ["0, 1, 2, 3, 4]"
print(nums[:-1])    # Slice indices can be negative; prints ["0, 1, 2, 3]"
nums[2:4] = [8, 9]  # Assign a new sublist to a slice
print(nums)   # Prints "[0, 1, 8, 9, 4]"
print (num[::-1]) #prints reverse order  

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


NameError: name 'num' is not defined

####Loops

You can loop over the elements of a list like this:

In [7]:
animals = ['cat', 'dog', 'monkey']  # double string and single string we can used both 
for animal in animals:
    print(animal)

cat
dog
monkey


If you want access to the index of each element within the body of a loop, use the built-in `enumerate` function:

In [ ]:
animals = ['cat', 'dog', 'monkey']

for idx, animal in enumerate(animals):
    print('#{}: {}'.format(idx + 1, animal))

####List comprehensions:

When programming, frequently we want to transform one type of data into another. As a simple example, consider the following code that computes square numbers:

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)

You can make this code simpler using a list comprehension:

In [8]:
nums = [0, 1, 2, 3, 4]

[x ** 2 for x in nums]

[0, 1, 4, 9, 16]

In [ ]:
nums = [0, 1, 2, 3, 4]

squares = [x ** 2 for x in nums]

print(squares)

List comprehensions can also contain conditions:

In [ ]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)

####Dictionaries

A dictionary stores (key, value) pairs. You can use it like this:

In [6]:
d = {'cat': 'clawy', 'dog': 'furry'}  # Create a new dictionary with some data
print(d)
print(d.items())

print(d['cat'])       # Get an entry from a dictionary; prints "clawy"
print('cat' in d)     # Check if a dictionary has a given key; prints "True"

{'cat': 'clawy', 'dog': 'furry'}
dict_items([('cat', 'clawy'), ('dog', 'furry')])
clawy
True


In [4]:
d['fish'] = 'glob_glob'    # Set an entry in a dictionary
print(d['fish'])      # Prints "glob_glob"

glob_glob


In [5]:
print(d)

{'cat': 'clawy', 'dog': 'furry', 'fish': 'glob_glob'}


In [ ]:
print(d['monkey'])  # KeyError: 'monkey' not a key of d

In [ ]:
del d['fish']        # Remove an element from a dictionary
print(d)     # KeyError: 'fish' not a key of d

In [ ]:
del d['fish']

You can find all you need to know about dictionaries in the [documentation](https://docs.python.org/2/library/stdtypes.html#dict).

It is easy to iterate over the keys in a dictionary:

In [7]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print('A {} has {} legs'.format(animal, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


Dictionary comprehensions: These are similar to list comprehensions, but allow you to easily construct dictionaries. For example:

In [13]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(type(even_num_to_square))
print(even_num_to_square)

<class 'dict'>
{0: 0, 2: 4, 4: 16}


####Sets

A set is an unordered collection of distinct elements. As a simple example, consider the following: 
NO repeatable value 

In [8]:
x = [1, 2]    
y = {1, 2, 3, 4,4}
print(type(x))   # list 
print(type(y))   # set 
print(y)

print(2 in x)
print(5 in y)

<class 'list'>
<class 'set'>
{1, 2, 3, 4}
True
False


In [5]:
animals = {'cat', 'dog'}
print(animals)
print('cat' in animals)   # Check if an element is in a set; prints "True"
print('fish' in animals)  # prints "False"

{'cat', 'dog'}
True
False


In [8]:
animals.add('cat')  # Adding an element that is already in the set does nothing
print(len(animals))       
animals.add('miek')
print(animals)
animals.remove('cat')    # Remove an element from a set
print(len(animals))       

3
{'miek', 'cat', 'dog'}
2


_Loops_: Iterating over a set has the same syntax as iterating over a list; however since sets are unordered, you cannot make assumptions about the order in which you visit the elements of the set:

In [9]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#{}: {}'.format(idx + 1, animal))

#1: fish
#2: cat
#3: dog


Set comprehensions: Like lists and dictionaries, we can easily construct sets using set comprehensions:

####Tuples

A tuple is an (immutable) ordered list of values. A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. Here is a trivial example: 
cannot change

In [6]:
t = (1, 2, 3,"hello")
print(t)
print(type(t))
t.index(3)

(1, 2, 3, 'hello')
<class 'tuple'>


2

In [9]:
del t[1]

TypeError: 'tuple' object doesn't support item deletion

Immutable: `tuple` object doesn't support item deletion.

In [13]:
d = {(x, x + 1): x**2 for x in range(10)}  # Create a dictionary with tuple keys
print(d)

print(d[(1, 2)])

t = (5, 6)       # Create a tuple
print(type(t))
print(d[t])       

{(0, 1): 0, (1, 2): 1, (2, 3): 4, (3, 4): 9, (4, 5): 16, (5, 6): 25, (6, 7): 36, (7, 8): 49, (8, 9): 64, (9, 10): 81}
1
<class 'tuple'>
25


###Functions

Python functions are defined using the `def` keyword. For example:

In [17]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'
# ----------------------- #
for x in [-1, 0, 1]:
    print(sign(x))
    


negative
zero
positive


We will often define functions to take optional keyword arguments, like this:

In [18]:
def hello(name, loud=False):
    if loud:
        print('HELLO, {}'.format(name.upper()))
    else:
        print('Hello, {}!'.format(name))
# ----------------------- #
hello('Bob')
hello('Fred', loud=True)

Hello, Bob!
HELLO, FRED


###Classes

The syntax for defining classes in Python is straightforward:

In [ ]:
class Greeter:

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)

# ----------------------- #
g = Greeter('Fred')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method; prints "Hello, Fred"
g.greet(loud=True)   # Call an instance method; prints "HELLO, FRED!"

##Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

To use Numpy, we first need to import the `numpy` package:

In [ ]:
import numpy as np

###Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [21]:
import numpy as np
b = np.array([[1,2,3],[4,5,6]])   # Create a 2x3 dimension array
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


Numpy also provides many functions to create arrays:

In [22]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [23]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

[[1. 1.]]


In [25]:
c = np.full((2,3), 7) # Create a constant array
print(c)

[[7 7 7]
 [7 7 7]]


In [ ]:
d = np.eye(4)        # Create a 2x2 identity matrix
print(d)

In [19]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

[[0.31964215 0.84401655]
 [0.5228753  0.55320097]]


###Array shape

In [21]:
a = np.array([[1,2,3,4], 
              [5,6,7,8], 
              [9,10,11,12]])
print(a.shape)

(3, 4)


Start from the first bracket, count the number of elements. This number will be the first dimension (first component of shape). After that move to next big bracket and count the number of elemnets, this is the second dimension and so on.

In [20]:
b = np.array([[[1, 2, 3], [4, 5, 6]], 
              [[7, 8, 9], [0, 1, 2]], 
              [[3, 4, 5], [6, 7, 8]],
              [[1, 4, 5], [8, 7, 8]]])
print(b.shape) # b shape is outer side to inner side 

(4, 2, 3)


###Array indexing

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [15]:
import numpy as np

# Create the following array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


A slice of an array is a view into the same data, so modifying it will modify the original array.

In [11]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a) 

2
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
x = np.array([[1, 2], 
              [3, 4]])
print(x)

# shallow copy (references are copied)
y = x
y[1][1] = 5
print(x)

# deep copy (values are copied)
z = np.copy(x)
z[1][1] = 10
print(x) 
print("z" , z)

[[1 2]
 [3 4]]
[[1 2]
 [3 5]]
[[1 2]
 [3 5]]
z [[ 1  2]
 [ 3 10]]


While assignment operator (`=`) performs a shallow copy, `.copy()` creates a copy of the `input` by recursively copying the values instead of references.

###Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.float64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

###Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

In [ ]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

In [ ]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

Note that `*` is elementwise multiplication, not matrix multiplication. We instead use the `dot` function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [ ]:
v = np.array([9, 10])
w = np.array([11, 12])

print(v.shape)
print(w.shape)

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

[9, 10] • [11, 12] = 9 * 11 + 10 * 12 = 219

You can also use the `@` operator which is equivalent to numpy's `dot` operator.

In [ ]:
print(v @ w)

In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
x = np.array([[1,2],[3,4]])
v = np.array([9, 10])

print(x.shape)
print(v.shape)

print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

In [ ]:
x = np.array([[1, 2, 4],[3, 4, 5]]) 
y = np.array([[2, 7, 8, 9], [1, 2, 3, 4], [8, 11, 1, 7]])

print(x.shape)
print(y.shape)

print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [29]:
x = np.array([[1,2],[3,4]])
print(x)
print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [ ]:
print(x)
print("transpose\n", x.T)

In [ ]:
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)

###Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [0, 1, 2]])
print("x :: ")
print(x)

v = np.array([1, 0, 1])
print("v :: ")
print(v)

z = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    z[i, :] = x[i, :] + v

print("z :: ")
print(z)

This works; however when the matrix `x` is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix `x` is equivalent to forming a matrix `vv` by stacking multiple copies of `v` vertically, then performing elementwise summation of `x` and `vv`. We could implement this approach like this:

In [ ]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

In [ ]:
z = x + vv  # Add x and vv elementwise
print(z)

Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version while using broadcasting:

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
print("x :: ")
print(x)

print("v :: ")
print(v)

z = x + v  # Add v to each row of x using broadcasting
print("z :: ")
print(z)

In [ ]:
x.shape, v.shape

The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the element-wise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

To get more sense of what is going on, try reading the explanation from the [documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or this [explanation](http://wiki.scipy.org/EricsBroadcastingDoc).

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the [documentation](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Here are some applications of broadcasting:

In [ ]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)

# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)

In an abstract way, the difference between `(R,)` and `(R, 1)` is the number of indices that we need to use. The first one is a vector whereas the second is a 2-D matrix with only one column. If we have a data with only 1-dimension, it is suggested by developers and the community that, we should be using a vector, not a matrix with a singleton dimension.

[Difference between numpy.array shape (R, 1) and (R,)](https://stackoverflow.com/a/22074424/6521550) 

In [ ]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
x = np.array([[1,2,3], [4,5,6]])
print(x)
print(x * 2)

Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the [numpy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.

##Matplotlib

Matplotlib is a plotting library. In this section give a brief introduction to the `matplotlib.pyplot` module, which provides a plotting system similar to that of MATLAB.

In [ ]:
import matplotlib.pyplot as plt

By running this special iPython command, we will be displaying plots inline:

In [ ]:
%matplotlib inline 
# Things we can ponder upon: What is inline display?

The command starting with `%` or `%%` are called magic functions. You can refer this documnetation to know more about [Magic Functions](https://ipython.readthedocs.io/en/stable/interactive/tutorial.html#magics-explained).

Using `inline` command ensures that Jupyter Notebooks show our plots in the notebook. Moreover you can store the ouputs produced, in the notebook itself. You can find a beautiful explanation [here](https://ipython.readthedocs.io/en/stable/interactive/plotting.html).

###Plotting

The most important function in `matplotlib` is plot, which allows you to plot 2D data. Here is a simple example:

In [ ]:
# Compute the x and y coordinates for points on a sine curve
x = np.arange(0, 3 * np.pi, 0.1)
y = np.sin(x)

# Plot the points using matplotlib
plt.plot(x, y)

With just a little bit of extra work we can easily plot multiple lines at once, and add a title, legend, and axis labels:

In [ ]:
y_sin = np.sin(x)
y_cos = np.cos(x)

# Plot the points using matplotlib
plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])

###Subplots 

You can plot different things in the same figure using the subplot function. Here is an example:

In [ ]:
# Compute the x and y coordinates for points on sine and cosine curves
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Set up a subplot grid that has height 2 and width 1,
# and set the first such subplot as active.
plt.subplot(2, 1, 1)

# Make the first plot
plt.plot(x, y_sin)
plt.title('Sine')

# Set the second subplot as active, and make the second plot.
plt.subplot(2, 1, 2)
plt.plot(x, y_cos)
plt.title('Cosine')

# Show the figure.
plt.show()

You can read much more about the `subplot` function in the [documentation](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.subplot).

##Pandas

Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool, built on top of the Python programming language. We will see a quick introduction of how can we load, analyze and manipulate a real world dataset using `pandas`. 

The primary data structures in *pandas* are implemented as two classes:

  * **`DataFrame`**, which is a 2-dimensional data structure that can store data of different types (including characters, integers, floating point values, categorical data and more) in columns. It is similar to a spreadsheet, a SQL table..

  * **`Series`**, which is a single column. A `DataFrame` contains one or more `Series` and a name for each `Series`.

We will only talk about `DataFrame` in this tutorial.

In [ ]:
import pandas as pd

We will load a sample dataset provided in Google Colab, called as  **California Housing Dataset**.



In [ ]:
df = pd.read_csv("/content/sample_data/california_housing_train.csv") 
# Reading a csv file and loading it as a dataframe

In [ ]:
df.head() # head() gives us the first 5 rows of the DataFrame.

In [ ]:
type(df) # Checking the type of 'df'. Surpise : it is DataFrame

To select a single column, use square brackets `[]` with the column name of the column of interest.

In [ ]:
# selecting a single column named 'housing_median_age'
housing_median_age = df["housing_median_age"] 
housing_median_age.head()

In [ ]:
type(housing_median_age) # Bonus question

If we want to select more than one column use a list of column names within the selection brackets `[]`.

In [ ]:
# selecting two columns namely : 'total_rooms' and 'total_bedrooms'
total_rooms_bed_rooms = df[["total_rooms", "total_bedrooms"]]
total_rooms_bed_rooms.head()

In [ ]:
total_rooms_bed_rooms.shape # The shape is arranged as (#rows, #columns)

How do I filter specific rows from a `DataFrame` ?

In [ ]:
housing_median_age_greater_than_10 = df[df["total_rooms"] > 2000]
print(housing_median_age_greater_than_10.shape) # Note the change in the shape 

If we require a subset of both rows and columns then just using the selection brackets `[]` is not sufficient anymore. 

We then, require `loc/iloc` operators in front of the selection brackets `[]`. 

In [ ]:
print(df.iloc[1, 4])

When using `loc/iloc`, the part before the comma is the rows, and the part after the comma is the columns we desire to select.

In [ ]:
print(df.iloc[11:15, 4]) # Using slicing for selecting rows from 11 till 14 

In [ ]:
print(df.loc[:, "total_rooms"])
# Difference between loc vs iloc

* `loc` is label-based, which means that you have to specify rows and columns based on their row and column labels. 
* `iloc` is integer index based, so you have to specify rows and columns by their integer index

How to calculate summary statistics ?

In [ ]:
df["housing_median_age"].mean()

In [ ]:
df[["total_rooms", "total_bedrooms"]].median()

The `describe()` method provides a quick overview of the numerical data in a DataFrame.
Note the columns with textual data are by default not taken into account by the `describe()` method.

In [ ]:
df[["total_rooms", "total_bedrooms"]].describe()

We can plot graphs for better visualization.

In [ ]:
df.hist('housing_median_age') 
# What does the graph signify ?

You can have a further reading on `pandas` and how to get started in the official [documentation](https://pandas.pydata.org/docs/getting_started/index.html#getting-started).

##Seaborn

Back to plotting again ??

`Seaborn` is a library for making statistical graphics in Python. It builds on top of `matplotlib` and integrates closely with `pandas` data structures.

`Seaborn` helps you explore and understand your data. Its plotting functions operate on dataframes and arrays containing whole datasets and internally perform the necessary semantic mapping and statistical aggregation to produce informative plots. Its dataset-oriented, declarative API lets you focus on what the different elements of your plots mean, rather than on the details of how to draw them.



In [ ]:
# Import seaborn
import seaborn as sns

In [ ]:
# Load an example dataset
penguins = sns.load_dataset("penguins")

In [ ]:
print(type(penguins))

In [ ]:
print(penguins.head())

In [ ]:
print(penguins.columns)

In [ ]:
sns.jointplot(data=penguins, x="bill_length_mm", y="bill_depth_mm", hue="species")

`jointplot()` plots the joint distribution between two variables along with each variable’s marginal distribution.

In [ ]:
sns.pairplot(data=penguins, hue="species")

`pairplot()` takes a broader view: it shows joint and marginal distributions for all pairwise relationships and for each variable, respectively.

In [ ]:
sns.displot(data=penguins, x="bill_length_mm", col="species", kde=True)

You can explore other type of plots here : [Seaborn Gallery](https://seaborn.pydata.org/examples/index.html)